apiVersion: v1
kind: Service
metadata:
  name: scribe
spec:
  selector:
    app: scribe
  ports:
    - protocol: TCP
      port: 1463
      targetPort: 1463

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scribe
spec:
  selector:
    matchLabels:
      app: scribe
  replicas: 1

  template:
    metadata:
      labels:
        app: scribe
    spec:
      containers:
        - name: main
          image: polonaiz/facebook-scribe
          imagePullPolicy: Always
          resources:
            limits:
              memory: 1Gi
              cpu: 500m
          ports:
            - containerPort: 1463
          volumeMounts:
            - mountPath: /data
              name: data-volume
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: scribe-data-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scribe-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
