apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scribe
spec:
  selector:
    matchLabels:
      app: scribe
  serviceName: scribe
  replicas: 1
  template:
    metadata:
      labels:
        app: scribe
    spec:
      containers:
        - name: main
          image: polonaiz/facebook-scribe
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 512Mi
              cpu: 250m
          ports:
            - containerPort: 1463
          volumeMounts:
            - mountPath: /data
              name: scribe-data
  volumeClaimTemplates:
    - metadata:
        name: scribe-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi

